# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the igrac branch
on:
  push:
    branches: [ igrac ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build and Push Docker Image	
    runs-on: ubuntu-16.04	
    steps:
    - name: Build and Publish the Docker Image	
      uses: elgohr/Publish-Docker-Github-Action@master	
      with:
        name: kartoza/geonode_django_base:igrac
        workdir: scripts/spcgeonode/django
        username: ${{ secrets.DOCKER_USERNAME }}	
        password: ${{ secrets.DOCKER_PASSWORD }}
